# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import servicegrpc_pb2 as servicegrpc__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in servicegrpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GRPCServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.request_action = channel.unary_unary(
                '/GRPCService/request_action',
                request_serializer=servicegrpc__pb2.GRPCActionRequest.SerializeToString,
                response_deserializer=servicegrpc__pb2.GRPCActionResponse.FromString,
                _registered_method=True)
        self.request_describe_target = channel.unary_unary(
                '/GRPCService/request_describe_target',
                request_serializer=servicegrpc__pb2.GRPCDescribeTargetRequest.SerializeToString,
                response_deserializer=servicegrpc__pb2.GRPCDescribeTargetResponse.FromString,
                _registered_method=True)
        self.request_input = channel.unary_stream(
                '/GRPCService/request_input',
                request_serializer=servicegrpc__pb2.GRPCInputRequest.SerializeToString,
                response_deserializer=servicegrpc__pb2.GRPCInputResponse.FromString,
                _registered_method=True)
        self.request_log = channel.unary_stream(
                '/GRPCService/request_log',
                request_serializer=servicegrpc__pb2.GRPCLogRequest.SerializeToString,
                response_deserializer=servicegrpc__pb2.GRPCLogResponse.FromString,
                _registered_method=True)
        self.request_run_image = channel.unary_unary(
                '/GRPCService/request_run_image',
                request_serializer=servicegrpc__pb2.GRPCRunImageRequest.SerializeToString,
                response_deserializer=servicegrpc__pb2.GRPCRunImageResponse.FromString,
                _registered_method=True)


class GRPCServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def request_action(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def request_describe_target(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def request_input(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def request_log(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def request_run_image(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GRPCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'request_action': grpc.unary_unary_rpc_method_handler(
                    servicer.request_action,
                    request_deserializer=servicegrpc__pb2.GRPCActionRequest.FromString,
                    response_serializer=servicegrpc__pb2.GRPCActionResponse.SerializeToString,
            ),
            'request_describe_target': grpc.unary_unary_rpc_method_handler(
                    servicer.request_describe_target,
                    request_deserializer=servicegrpc__pb2.GRPCDescribeTargetRequest.FromString,
                    response_serializer=servicegrpc__pb2.GRPCDescribeTargetResponse.SerializeToString,
            ),
            'request_input': grpc.unary_stream_rpc_method_handler(
                    servicer.request_input,
                    request_deserializer=servicegrpc__pb2.GRPCInputRequest.FromString,
                    response_serializer=servicegrpc__pb2.GRPCInputResponse.SerializeToString,
            ),
            'request_log': grpc.unary_stream_rpc_method_handler(
                    servicer.request_log,
                    request_deserializer=servicegrpc__pb2.GRPCLogRequest.FromString,
                    response_serializer=servicegrpc__pb2.GRPCLogResponse.SerializeToString,
            ),
            'request_run_image': grpc.unary_unary_rpc_method_handler(
                    servicer.request_run_image,
                    request_deserializer=servicegrpc__pb2.GRPCRunImageRequest.FromString,
                    response_serializer=servicegrpc__pb2.GRPCRunImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GRPCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GRPCService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GRPCService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def request_action(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GRPCService/request_action',
            servicegrpc__pb2.GRPCActionRequest.SerializeToString,
            servicegrpc__pb2.GRPCActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def request_describe_target(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GRPCService/request_describe_target',
            servicegrpc__pb2.GRPCDescribeTargetRequest.SerializeToString,
            servicegrpc__pb2.GRPCDescribeTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def request_input(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/GRPCService/request_input',
            servicegrpc__pb2.GRPCInputRequest.SerializeToString,
            servicegrpc__pb2.GRPCInputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def request_log(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/GRPCService/request_log',
            servicegrpc__pb2.GRPCLogRequest.SerializeToString,
            servicegrpc__pb2.GRPCLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def request_run_image(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GRPCService/request_run_image',
            servicegrpc__pb2.GRPCRunImageRequest.SerializeToString,
            servicegrpc__pb2.GRPCRunImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
