# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: servicegrpc.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'servicegrpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11servicegrpc.proto\"0\n\x11GRPCActionRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\"A\n\x12GRPCActionResponse\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\".\n\x19GRPCDescribeTargetRequest\x12\x11\n\ttarget_id\x18\x01 \x01(\t\"D\n\x1aGRPCDescribeTargetResponse\x12\x11\n\ttarget_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x1f\n\x10GRPCInputRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\".\n\x11GRPCInputResponse\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"%\n\x0eGRPCLogRequest\x12\x13\n\x0blogger_name\x18\x01 \x01(\t\"\x1f\n\x0fGRPCLogResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x8f\x01\n\x13GRPCRunImageRequest\x12\x11\n\ttarget_id\x18\x01 \x01(\t\x12\x13\n\x0b\x62reakpoints\x18\x02 \x03(\x04\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x0e\n\x06\x64igest\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x12$\n\x1c\x65xecution_timeout_in_seconds\x18\x06 \x01(\x02\"\xb0\x01\n\x14GRPCRunImageResponse\x12\x11\n\ttarget_id\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0e\n\x06\x64igest\x18\x03 \x01(\t\x12\x0e\n\x06output\x18\x04 \x01(\x0c\x12\x0e\n\x06status\x18\x05 \x01(\t\x12 \n\x18load_duration_in_seconds\x18\x06 \x01(\x02\x12%\n\x1d\x65xecution_duration_in_seconds\x18\x07 \x01(\x02\x32\xcc\x02\n\x0bGRPCService\x12\x39\n\x0erequest_action\x12\x12.GRPCActionRequest\x1a\x13.GRPCActionResponse\x12R\n\x17request_describe_target\x12\x1a.GRPCDescribeTargetRequest\x1a\x1b.GRPCDescribeTargetResponse\x12\x38\n\rrequest_input\x12\x11.GRPCInputRequest\x1a\x12.GRPCInputResponse0\x01\x12\x32\n\x0brequest_log\x12\x0f.GRPCLogRequest\x1a\x10.GRPCLogResponse0\x01\x12@\n\x11request_run_image\x12\x14.GRPCRunImageRequest\x1a\x15.GRPCRunImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'servicegrpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRPCACTIONREQUEST']._serialized_start=21
  _globals['_GRPCACTIONREQUEST']._serialized_end=69
  _globals['_GRPCACTIONRESPONSE']._serialized_start=71
  _globals['_GRPCACTIONRESPONSE']._serialized_end=136
  _globals['_GRPCDESCRIBETARGETREQUEST']._serialized_start=138
  _globals['_GRPCDESCRIBETARGETREQUEST']._serialized_end=184
  _globals['_GRPCDESCRIBETARGETRESPONSE']._serialized_start=186
  _globals['_GRPCDESCRIBETARGETRESPONSE']._serialized_end=254
  _globals['_GRPCINPUTREQUEST']._serialized_start=256
  _globals['_GRPCINPUTREQUEST']._serialized_end=287
  _globals['_GRPCINPUTRESPONSE']._serialized_start=289
  _globals['_GRPCINPUTRESPONSE']._serialized_end=335
  _globals['_GRPCLOGREQUEST']._serialized_start=337
  _globals['_GRPCLOGREQUEST']._serialized_end=374
  _globals['_GRPCLOGRESPONSE']._serialized_start=376
  _globals['_GRPCLOGRESPONSE']._serialized_end=407
  _globals['_GRPCRUNIMAGEREQUEST']._serialized_start=410
  _globals['_GRPCRUNIMAGEREQUEST']._serialized_end=553
  _globals['_GRPCRUNIMAGERESPONSE']._serialized_start=556
  _globals['_GRPCRUNIMAGERESPONSE']._serialized_end=732
  _globals['_GRPCSERVICE']._serialized_start=735
  _globals['_GRPCSERVICE']._serialized_end=1067
# @@protoc_insertion_point(module_scope)
